### PR TITLE
security patch

### PR DESCRIPTION
**Pull request by txm**

### CODE REVIEW

**Comment by txm** [comment]
```
~/security/ember-cli-less (feature/cve-lodash) $ node_modules/.bin/ember try:one ember-lts-3.4
(node:54644) ExperimentalWarning: The fs.promises API is experimental
added 2 packages from 2 contributors, removed 5 packages, updated 3 packages and audited 42106 packages in 6.109s
found 5 vulnerabilities (1 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
removed 17 packages and audited 41909 packages in 5.54s
found 5 vulnerabilities (1 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details

=== Scenario: ember-lts-3.4 ====================================================

(node:54662) ExperimentalWarning: The fs.promises API is experimental

Missing npm packages:
Package: ember-source
  * Specified: ~3.4.0
  * Installed: (not installed)

Run `npm install` to install missing dependencies.



Stack Trace and Error Report: /var/folders/7n/rm7jd_l54sg9zvbpfdp0l61m0000gn/T/error.dump.deb7f1917353dd4b3ca8614cd611f762.log
An error occurred in the constructor for ember-cli-dependency-checker at /Users/andrewmcgregor/security/ember-cli-less/node_modules/ember-cli-dependency-checker


Result: false
---


------ RESULTS ------

Scenario ember-lts-3.4: FAIL
Command run: ember test

1 scenarios failed
0 scenarios succeeded
1 scenarios run

```

**Comment by txm** [comment]
Ah, so the problem is in master :/

**Comment by knownasilya** [comment]
Probably something with travis and ember-try.. will investigate later today.

**Comment by txm** [comment]
It fails locally too:

```
$ npm i && node_modules/.bin/ember try:one ember-lts-3.4 --config-path="config/ember-try.js"
```

The _only_ way I could get it working was to set ember-source 3.4 in package.json, hth.

**Comment by knownasilya** [comment]
Yeah, maybe ember-try or ember-cli needs an update or maybe the try config needs updating. Unsure, but I think I've seen this before but don't remember where! lol

**Comment by cythrawll** [comment]
Hi, so I played around with this, and seems simply updating ember-try to 1.2.1 fixes the issue.

**Comment by txm** [comment]
Good spot.  Kicking myself now..

**Pull request merged**
