### PR TITLE
Vulnerable fix

### PR DESCRIPTION
**Pull request by abrahamspaa**
Bump `broccoli-less-single` package versions to address below,

https://github.com/advisories/GHSA-fvqr-27wr-82fm
https://github.com/advisories/GHSA-35jh-r3h4-6jhm

### CODE REVIEW

**Comment by abrahamspaa** [comment]
Thank you for merging @knownasilya. Can we get this release, please?

**Comment by knownasilya** [comment]
Will release today

**Comment by abrahamspaa** [comment]
Thank you @knownasilya

**Comment by knownasilya** [comment]
Published in v3.0.2

**Pull request merged**
